### ISSUE TITLE
Hammer and sickle images

### ISSUE THREAD

**Issue by Tyrannicodin** [JoanRiosiPla/communopoly#2]
I've been looking at making my own version of this, but can't find a sickle or hammer that are separate from each other, could you please share where you got the source images from?

**Comment by MaiRiosIPla** [comment]
I couldn't find them either, so I drew them. I'm going to upload them to source, but I encourage you to try and make your own.

**Comment by Tyrannicodin** [comment]
Yeah, I'll have a go at it. Was just trying to skip the little bit of work it would take :P

**Comment by MaiRiosIPla** [comment]
Ok, you should be able to see them now.
